#import <UIKit/UIKit.h>
#import <Security/Security.h>
#import <objc/runtime.h>
#import <objc/message.h>

static NSString * const EONVIDIAService=@"EOBOTER.NVIDIA";
static NSString * const EONVIDIAAccount=@"API_KEY";
static NSString * const EOModel=@"google/diffusiongemma-26b-a4b-it";
@interface EOPassThroughWindow:UIWindow @property(nonatomic,weak)UIView*interactiveRoot;@end
@implementation EOPassThroughWindow
- (UIView*)hitTest:(CGPoint)p withEvent:(UIEvent*)e{UIView*h=[super hitTest:p withEvent:e];if(!h||h==self||h==self.rootViewController.view)return nil;return(self.interactiveRoot&&[h isDescendantOfView:self.interactiveRoot])?h:nil;}
@end

@interface EOBOTEROverlay:NSObject
@property(nonatomic,strong)EOPassThroughWindow*overlayWindow;@property(nonatomic,strong)UIButton*bubble;@property(nonatomic,strong)UIView*panel;
@property(nonatomic,strong)UITextView*logView;@property(nonatomic,strong)UILabel*marketLabel;@property(nonatomic,strong)UILabel*statusLabel;@property(nonatomic,strong)UITextField*keyField;
@property(nonatomic,strong)NSArray<NSDictionary*>*lastCandidates;@property(nonatomic,strong)NSDictionary*externalMarketSnapshot;@property(nonatomic,strong)NSArray*externalCandles;@property(nonatomic,strong)NSDate*externalMarketUpdatedAt;@property(nonatomic,strong)NSDictionary*buyTarget;@property(nonatomic,strong)NSDictionary*sellTarget;@property(nonatomic,strong)NSDictionary*snapshot;@property(nonatomic,copy)NSString*learnDirection;@property(nonatomic,strong)UITapGestureRecognizer*learnTap;@property(nonatomic,strong)NSMutableDictionary<NSString*,NSDictionary*>*dataTargets;@property(nonatomic,strong)NSArray<NSString*>*mapQueue;@property(nonatomic)NSInteger mapIndex;
@end

static IMP EOOrigSetAmount=NULL,EOOrigSetAsset=NULL,EOOrigSetRateIndex=NULL;
static void EOSetAmountHook(id self,SEL _cmd,id amount){if(EOOrigSetAmount)((void(*)(id,SEL,id))EOOrigSetAmount)(self,_cmd,amount);if(amount)dispatch_async(dispatch_get_main_queue(),^{[[EOBOTEROverlay shared] applyInternalField:@"investment" value:[amount description]];});}
static void EOSetAssetHook(id self,SEL _cmd,id asset,NSInteger assetId,NSInteger digits){if(EOOrigSetAsset)((void(*)(id,SEL,id,NSInteger,NSInteger))EOOrigSetAsset)(self,_cmd,asset,assetId,digits);if(asset)dispatch_async(dispatch_get_main_queue(),^{[[EOBOTEROverlay shared] applyInternalField:@"asset" value:[asset description]];});}
static void EOSetRateIndexHook(id self,SEL _cmd,NSInteger rate,NSInteger rateIndex){if(EOOrigSetRateIndex)((void(*)(id,SEL,NSInteger,NSInteger))EOOrigSetRateIndex)(self,_cmd,rate,rateIndex);dispatch_async(dispatch_get_main_queue(),^{[[EOBOTEROverlay shared] log:[NSString stringWithFormat:@"INTERNAL rate=%ld rateIndex=%ld (diagnostic; not treated as price)",(long)rate,(long)rateIndex]];});}
static BOOL EOTypeLooksObjectSetter(Method m,NSUInteger argc){if(!m||method_getNumberOfArguments(m)!=argc)return NO;char ret[8]={0};method_getReturnType(m,ret,sizeof(ret));if(ret[0]!='v')return NO;char arg[16]={0};method_getArgumentType(m,2,arg,sizeof(arg));return arg[0]=='@';}
static BOOL EOTypeLooksIntegerPairSetter(Method m){if(!m||method_getNumberOfArguments(m)!=4)return NO;char ret[8]={0},a[16]={0},b[16]={0};method_getReturnType(m,ret,sizeof(ret));method_getArgumentType(m,2,a,sizeof(a));method_getArgumentType(m,3,b,sizeof(b));return ret[0]=='v'&&(a[0]=='q'||a[0]=='i'||a[0]=='l')&&(b[0]=='q'||b[0]=='i'||b[0]=='l');}

@implementation EOBOTEROverlay
+ (instancetype)shared{static id x;static dispatch_once_t o;dispatch_once(&o,^{x=[self new];});return x;}
- (void)applyInternalField:(NSString*)key value:(NSString*)value{if(!key.length||!value.length)return;NSMutableDictionary*m=[self.externalMarketSnapshot mutableCopy]?:[NSMutableDictionary dictionary];m[key]=value;self.externalMarketSnapshot=m;self.externalMarketUpdatedAt=[NSDate date];}
- (void)installInternalMarketCapture{Class cls=objc_getClass("ExpertOptionPlotView");if(!cls){[self log:@"INTERNAL FEED: ExpertOptionPlotView not loaded"];return;}Method ma=class_getInstanceMethod(cls,NSSelectorFromString(@"setAmount:"));if(ma&&method_getClass(ma)!=cls)ma=NULL;if(EOTypeLooksObjectSetter(ma,3)){EOOrigSetAmount=method_setImplementation(ma,(IMP)EOSetAmountHook);[self log:@"INTERNAL FEED: amount capture active"];}else [self log:@"INTERNAL FEED: setAmount signature skipped"];
 Method ms=class_getInstanceMethod(cls,NSSelectorFromString(@"setAsset:assetId:digits:"));if(ms&&method_getClass(ms)!=cls)ms=NULL;if(ms&&method_getNumberOfArguments(ms)==5){char r[8]={0},a[16]={0},b[16]={0},d[16]={0};method_getReturnType(ms,r,sizeof(r));method_getArgumentType(ms,2,a,sizeof(a));method_getArgumentType(ms,3,b,sizeof(b));method_getArgumentType(ms,4,d,sizeof(d));if(r[0]=='v'&&a[0]=='@'&&(b[0]=='q'||b[0]=='i'||b[0]=='l')&&(d[0]=='q'||d[0]=='i'||d[0]=='l')){EOOrigSetAsset=method_setImplementation(ms,(IMP)EOSetAssetHook);[self log:@"INTERNAL FEED: asset capture active"];}else [self log:@"INTERNAL FEED: setAsset signature skipped"];}
 Method mr=class_getInstanceMethod(cls,NSSelectorFromString(@"setRateIndex:rateIndex:"));if(mr&&method_getClass(mr)!=cls)mr=NULL;if(EOTypeLooksIntegerPairSetter(mr)){EOOrigSetRateIndex=method_setImplementation(mr,(IMP)EOSetRateIndexHook);[self log:@"INTERNAL FEED: rate capture active"];}else [self log:@"INTERNAL FEED: setRateIndex signature skipped"];}


- (void)log:(NSString*)s{if(!s.length)return;NSLog(@"[EOBOTER] %@",s);dispatch_async(dispatch_get_main_queue(),^{if(!self.logView)return;NSString*n=self.logView.text.length?[self.logView.text stringByAppendingFormat:@"\n%@",s]:s;NSArray*r=[n componentsSeparatedByString:@"\n"];if(r.count>120)n=[[r subarrayWithRange:NSMakeRange(r.count-120,120)]componentsJoinedByString:@"\n"];self.logView.text=n;[self.logView scrollRangeToVisible:NSMakeRange(n.length,0)];});}
- (void)install{dispatch_async(dispatch_get_main_queue(),^{if(self.overlayWindow)return;CGRect s=UIScreen.mainScreen.bounds;self.overlayWindow=[[EOPassThroughWindow alloc]initWithFrame:s];self.overlayWindow.windowLevel=UIWindowLevelAlert+100;self.overlayWindow.backgroundColor=UIColor.clearColor;UIViewController*vc=[UIViewController new];vc.view.backgroundColor=UIColor.clearColor;self.overlayWindow.rootViewController=vc;self.overlayWindow.hidden=NO;UIButton*b=[UIButton buttonWithType:UIButtonTypeSystem];b.frame=CGRectMake(s.size.width-72,150,56,56);b.layer.cornerRadius=28;b.backgroundColor=[UIColor colorWithWhite:.08 alpha:.94];[b setTitle:@"EO" forState:0];[b setTitleColor:UIColor.whiteColor forState:0];b.titleLabel.font=[UIFont boldSystemFontOfSize:16];[b addTarget:self action:@selector(togglePanel) forControlEvents:UIControlEventTouchUpInside];[b addGestureRecognizer:[[UIPanGestureRecognizer alloc]initWithTarget:self action:@selector(drag:)]];[vc.view addSubview:b];self.bubble=b;self.overlayWindow.interactiveRoot=b;});}
- (void)drag:(UIPanGestureRecognizer*)g{CGPoint d=[g translationInView:g.view.superview],c=g.view.center;c.x+=d.x;c.y+=d.y;CGRect s=UIScreen.mainScreen.bounds;c.x=MAX(28,MIN(s.size.width-28,c.x));c.y=MAX(50,MIN(s.size.height-50,c.y));g.view.center=c;[g setTranslation:CGPointZero inView:g.view.superview];}
- (UIButton*)btn:(NSString*)t frame:(CGRect)f action:(SEL)a{UIButton*b=[UIButton buttonWithType:UIButtonTypeSystem];b.frame=f;b.layer.cornerRadius=9;b.backgroundColor=[UIColor colorWithWhite:.16 alpha:1];[b setTitle:t forState:0];[b setTitleColor:UIColor.whiteColor forState:0];b.titleLabel.font=[UIFont boldSystemFontOfSize:11];[b addTarget:self action:a forControlEvents:UIControlEventTouchUpInside];return b;}
- (void)togglePanel{if(self.panel){[self.panel removeFromSuperview];self.panel=nil;self.logView=nil;self.overlayWindow.interactiveRoot=self.bubble;return;}CGRect s=UIScreen.mainScreen.bounds;CGFloat w=s.size.width-16,h=MIN(760,s.size.height-45);UIView*p=[[UIView alloc]initWithFrame:CGRectMake(8,35,w,h)];p.backgroundColor=[UIColor colorWithWhite:.04 alpha:.985];p.layer.cornerRadius=20;UILabel*t=[[UILabel alloc]initWithFrame:CGRectMake(14,10,w-70,30)];t.text=@"EOBOTER • LIVE LAB";t.textColor=UIColor.whiteColor;t.font=[UIFont boldSystemFontOfSize:20];[p addSubview:t];[p addSubview:[self btn:@"×" frame:CGRectMake(w-52,6,42,38) action:@selector(togglePanel)]];
if(!self.dataTargets)self.dataTargets=[NSMutableDictionary dictionary];self.statusLabel=[[UILabel alloc]initWithFrame:CGRectMake(14,43,w-28,28)];self.statusLabel.text=@"Demo verification • AI never auto-executes";self.statusLabel.textColor=UIColor.lightGrayColor;self.statusLabel.font=[UIFont systemFontOfSize:10];[p addSubview:self.statusLabel];
self.marketLabel=[[UILabel alloc]initWithFrame:CGRectMake(14,72,w-28,66)];self.marketLabel.numberOfLines=4;self.marketLabel.text=@"Asset: —\nInvestment: —  Expiry: —  Payout: —\nBUY/SELL: not mapped";self.marketLabel.textColor=UIColor.whiteColor;self.marketLabel.font=[UIFont monospacedSystemFontOfSize:11 weight:UIFontWeightRegular];[p addSubview:self.marketLabel];
CGFloat bw=(w-40)/3;[p addSubview:[self btn:@"CAPTURE" frame:CGRectMake(10,142,bw,38) action:@selector(captureSnapshot)]];[p addSubview:[self btn:@"MARKET DATA" frame:CGRectMake(20+bw,142,bw,38) action:@selector(showMarketDataStatus)]];[p addSubview:[self btn:@"DEBUG MAP" frame:CGRectMake(30+2*bw,142,bw,38) action:@selector(debugMap)]];CGFloat hw=(w-30)/2;[p addSubview:[self btn:@"LEARN BUY" frame:CGRectMake(10,184,hw,36) action:@selector(learnBuy)]];[p addSubview:[self btn:@"LEARN SELL" frame:CGRectMake(20+hw,184,hw,36) action:@selector(learnSell)]];
self.keyField=[[UITextField alloc]initWithFrame:CGRectMake(10,226,w-105,38)];self.keyField.secureTextEntry=YES;self.keyField.placeholder=@"NVIDIA API key";self.keyField.textColor=UIColor.whiteColor;self.keyField.backgroundColor=[UIColor colorWithWhite:.11 alpha:1];self.keyField.layer.cornerRadius=8;self.keyField.leftView=[[UIView alloc]initWithFrame:CGRectMake(0,0,10,1)];self.keyField.leftViewMode=UITextFieldViewModeAlways;[p addSubview:self.keyField];[p addSubview:[self btn:@"SAVE" frame:CGRectMake(w-87,226,77,38) action:@selector(saveKey)]];
[p addSubview:[self btn:@"ANALYZE NOW • DIFFUSIONGEMMA" frame:CGRectMake(10,272,w-125,42) action:@selector(analyzeNow)]];[p addSubview:[self btn:@"COPY LOG" frame:CGRectMake(w-105,272,95,42) action:@selector(copyLog)]];
self.logView=[[UITextView alloc]initWithFrame:CGRectMake(10,322,w-20,h-332)];self.logView.editable=NO;self.logView.selectable=YES;self.logView.backgroundColor=[UIColor colorWithWhite:.085 alpha:1];self.logView.textColor=UIColor.whiteColor;self.logView.font=[UIFont monospacedSystemFontOfSize:9.5 weight:UIFontWeightRegular];self.logView.layer.cornerRadius=10;[p addSubview:self.logView];[self.overlayWindow.rootViewController.view addSubview:p];self.panel=p;self.overlayWindow.interactiveRoot=p;[self startMarketFeed];[self installInternalMarketCapture];[self log:@"LIVE LAB ready • internal market capture active"];}

- (void)copyLog{NSString*s=self.logView.text?:@"";if(!s.length){[self log:@"COPY LOG: nothing to copy"];return;}UIPasteboard.generalPasteboard.string=s;self.statusLabel.text=[NSString stringWithFormat:@"Copied log • %lu chars",(unsigned long)s.length];}

- (NSData*)keyData:(NSString*)s{return[s dataUsingEncoding:NSUTF8StringEncoding];}
- (NSDictionary*)keyQuery{return@{(__bridge id)kSecClass:(__bridge id)kSecClassGenericPassword,(__bridge id)kSecAttrService:EONVIDIAService,(__bridge id)kSecAttrAccount:EONVIDIAAccount};}
- (void)saveKey{NSString*k=[self.keyField.text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if(!k.length){[self log:@"NVIDIA key empty"];return;}NSMutableDictionary*q=[[self keyQuery]mutableCopy];SecItemDelete((__bridge CFDictionaryRef)q);q[(__bridge id)kSecValueData]=[self keyData:k];q[(__bridge id)kSecAttrAccessible]=(__bridge id)kSecAttrAccessibleWhenUnlockedThisDeviceOnly;OSStatus st=SecItemAdd((__bridge CFDictionaryRef)q,NULL);self.keyField.text=@"";[self log:st==errSecSuccess?@"NVIDIA key saved in Keychain": [NSString stringWithFormat:@"Keychain save failed: %d",(int)st]];}
- (NSString*)readKey{NSMutableDictionary*q=[[self keyQuery]mutableCopy];q[(__bridge id)kSecReturnData]=@YES;q[(__bridge id)kSecMatchLimit]=(__bridge id)kSecMatchLimitOne;CFTypeRef out=NULL;if(SecItemCopyMatching((__bridge CFDictionaryRef)q,&out)!=errSecSuccess)return nil;NSData*d=CFBridgingRelease(out);return[[NSString alloc]initWithData:d encoding:NSUTF8StringEncoding];}

- (UIWindow*)hostWindow{for(UIScene*sc in UIApplication.sharedApplication.connectedScenes)if(sc.activationState==UISceneActivationStateForegroundActive&&[sc isKindOfClass:UIWindowScene.class])for(UIWindow*w in((UIWindowScene*)sc).windows)if(w!=self.overlayWindow&&!w.hidden&&w.alpha>.01&&w.windowLevel==UIWindowLevelNormal)return w;return nil;}
- (NSString*)text:(UIView*)v{NSMutableArray*a=[NSMutableArray array];if([v isKindOfClass:UILabel.class]&&((UILabel*)v).text.length)[a addObject:((UILabel*)v).text];if([v isKindOfClass:UIButton.class]){NSString*x=[((UIButton*)v)titleForState:0];if(x.length)[a addObject:x];}for(NSString*x in@[v.accessibilityLabel?:@"",v.accessibilityValue?:@"",v.accessibilityIdentifier?:@""])if(x.length)[a addObject:x];return[[a componentsJoinedByString:@" | "]stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];}
- (BOOL)rn:(NSString*)c{return[c containsString:@"RCT"]||[c containsString:@"RN"]||[c containsString:@"Fabric"]||[c containsString:@"ExpertOption"]||[c containsString:@"Plot"];}
- (void)walk:(UIView*)v out:(NSMutableArray*)o depth:(NSInteger)d{if(!v||d>26||v.hidden||v.alpha<.02||o.count>=1800)return;CGRect r=[v convertRect:v.bounds toView:nil],scr=UIScreen.mainScreen.bounds;if(CGRectIsEmpty(r)||r.size.width<3||r.size.height<3||!CGRectIntersectsRect(r,scr))return;NSString*c=NSStringFromClass(v.class)?:@"",*tx=[self text:v];BOOL act=[v isKindOfClass:UIControl.class]||v.gestureRecognizers.count>0||v.isAccessibilityElement;if(tx.length||[self rn:c]||act)[o addObject:@{@"view":v,@"class":c,@"text":tx?:@"",@"act":@(act),@"rn":@([self rn:c]),@"x":@(r.origin.x),@"y":@(r.origin.y),@"w":@(r.size.width),@"h":@(r.size.height)}];for(UIView*s in[v.subviews copy])[self walk:s out:o depth:d+1];}
- (NSString*)deepText:(UIView*)v{NSMutableArray*a=[NSMutableArray array];[self collectTextFromView:v into:a depth:4];return[a componentsJoinedByString:@" | "];}
- (UIView*)bestViewNearX:(CGFloat)x y:(CGFloat)y in:(NSArray*)items{UIView*best=nil;CGFloat score=CGFLOAT_MAX;for(NSDictionary*d in items){UIView*v=d[@"view"];CGRect r=[v convertRect:v.bounds toView:nil];if(r.size.width<8||r.size.height<8)continue;CGFloat cx=CGRectGetMidX(r),cy=CGRectGetMidY(r);CGFloat s=hypot(cx-x,cy-y)+0.02*r.size.width*r.size.height;if(s<score){score=s;best=v;}}return best;}
- (NSString*)numberToken:(NSString*)s{NSRegularExpression*re=[NSRegularExpression regularExpressionWithPattern:@"(?<![0-9])(?:[0-9]+\\.[0-9]{3,6})(?![0-9])" options:0 error:nil];NSTextCheckingResult*m=[re firstMatchInString:s options:0 range:NSMakeRange(0,s.length)];return m?[s substringWithRange:m.range]:@"—";}
- (void)autoMapFrom:(NSArray*)a{CGRect s=UIScreen.mainScreen.bounds;UIView*asset=[self bestViewNearX:s.size.width*.5 y:s.size.height*.17 in:a];UIView*expiry=[self bestViewNearX:s.size.width*.25 y:s.size.height*.84 in:a];UIView*amount=[self bestViewNearX:s.size.width*.72 y:s.size.height*.84 in:a];UIView*buy=[self bestViewNearX:s.size.width*.28 y:s.size.height*.91 in:a];UIView*sell=[self bestViewNearX:s.size.width*.72 y:s.size.height*.91 in:a];if(asset)self.dataTargets[@"ASSET"]=[self dictForView:asset text:[self deepText:asset]];if(expiry)self.dataTargets[@"EXPIRY"]=[self dictForView:expiry text:[self deepText:expiry]];if(amount)self.dataTargets[@"AMOUNT"]=[self dictForView:amount text:[self deepText:amount]];if(!self.buyTarget&&buy)self.buyTarget=[self dictForView:buy text:[self deepText:buy]];if(!self.sellTarget&&sell)self.sellTarget=[self dictForView:sell text:[self deepText:sell]];}
- (void)debugMap{UIWindow*w=[self hostWindow];if(!w)return;NSMutableArray*a=[NSMutableArray array];[self walk:w out:a depth:0];[self log:@"--- DEBUG TEXT ---"];NSInteger n=0;for(NSDictionary*d in a){NSString*cl=d[@"class"];if(!([cl containsString:@"Paragraph"]||[cl containsString:@"TextView"]))continue;NSString*t=[self deepText:d[@"view"]];if(!t.length)continue;if(n++>=70)break;[self log:[NSString stringWithFormat:@"%@ %.0f,%.0f %.0fx%.0f | %@",cl,[d[@"x"]doubleValue],[d[@"y"]doubleValue],[d[@"w"]doubleValue],[d[@"h"]doubleValue],t]];}NSDictionary*x=[self autoTextSnapshot:a];[self log:[NSString stringWithFormat:@"CLASSIFIED asset=%@ price=%@ amount=%@ expiry=%@ payout=%@",x[@"asset"],x[@"price"],x[@"investment"],x[@"expiry"],x[@"payout"]]];}

- (NSString*)regexFirst:(NSString*)p text:(NSString*)s{NSRegularExpression*r=[NSRegularExpression regularExpressionWithPattern:p options:NSRegularExpressionCaseInsensitive error:nil];NSTextCheckingResult*m=[r firstMatchInString:s options:0 range:NSMakeRange(0,s.length)];return m?[s substringWithRange:m.range]:nil;}
- (NSDictionary*)autoTextSnapshot:(NSArray*)items{NSString*asset=nil,*amount=nil,*expiry=nil,*payout=nil,*price=nil;for(NSDictionary*d in items){NSString*cl=d[@"class"];if(!([cl containsString:@"Paragraph"]||[cl containsString:@"TextView"]))continue;NSString*t=[self deepText:d[@"view"]];CGFloat y=[d[@"y"]doubleValue];if(!asset)asset=[self regexFirst:@"[A-Z]{3}\\s*/\\s*[A-Z]{3}(?:\\s*\\(OTC\\))?" text:t];if(!amount&&y>600)amount=[self regexFirst:@"\\$\\s*[0-9]+(?:\\.[0-9]+)?" text:t];if(!expiry&&y>600)expiry=[self regexFirst:@"(?:[0-9]{1,2}:)?[0-9]{2}:[0-9]{2}" text:t];if(!payout&&y>650)payout=[self regexFirst:@"[0-9]{1,3}%" text:t];if(!price&&y>150&&y<750)price=[self regexFirst:@"[0-9]+\\.[0-9]{3,6}" text:t];}return@{@"asset":asset?:@"—",@"price":price?:@"—",@"investment":amount?:@"—",@"expiry":expiry?:@"—",@"payout":payout?:@"—"};}
- (NSDictionary*)normalizedMarketSnapshot:(NSDictionary*)raw{
 if(![raw isKindOfClass:NSDictionary.class])return nil;
 NSMutableDictionary*out=[NSMutableDictionary dictionary];
 NSDictionary*aliases=@{@"asset":@[@"asset",@"symbol"],@"price":@[@"price",@"close",@"rate"],@"investment":@[@"investment",@"amount"],@"expiry":@[@"expiry",@"expiration",@"expTime"],@"payout":@[@"payout",@"profit"]};
 for(NSString*dst in aliases){for(NSString*src in aliases[dst]){id v=raw[src];if(v&&v!=NSNull.null){NSString*s=[v isKindOfClass:NSString.class]?v:[v description];if(s.length){out[dst]=s;break;}}}}
 return out.count?out:nil;
}
- (void)applyExternalMarketSnapshot:(NSDictionary*)raw{
 NSDictionary*n=[self normalizedMarketSnapshot:raw];if(!n){[self log:@"MARKET DATA rejected: empty/unsupported snapshot"];return;}
 self.externalMarketSnapshot=n;
 [self log:[NSString stringWithFormat:@"MARKET DATA accepted asset=%@ price=%@ amount=%@ expiry=%@ payout=%@",n[@"asset"]?:@"—",n[@"price"]?:@"—",n[@"investment"]?:@"—",n[@"expiry"]?:@"—",n[@"payout"]?:@"—"]];
}
- (NSString*)marketFeedPath{return [NSTemporaryDirectory() stringByAppendingPathComponent:@"eoboter_market.json"];}
- (void)startMarketFeed{[self pollMarketFeed];}
- (void)pollMarketFeed{NSString*p=[self marketFeedPath];NSData*d=[NSData dataWithContentsOfFile:p options:0 error:nil];if(d.length){NSDictionary*j=[NSJSONSerialization JSONObjectWithData:d options:0 error:nil];if([j isKindOfClass:NSDictionary.class]){NSNumber*ts=j[@"timestamp"];NSTimeInterval now=NSDate.date.timeIntervalSince1970;if(!ts||fabs(now-ts.doubleValue)<=20.0)[self ingestMarketFeed:j];}}dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(1*NSEC_PER_SEC)),dispatch_get_main_queue(),^{[self pollMarketFeed];});}
- (void)ingestMarketFeed:(NSDictionary*)payload{
 NSDictionary*raw=[payload[@"snapshot"] isKindOfClass:NSDictionary.class]?payload[@"snapshot"]:payload;NSDictionary*n=[self normalizedMarketSnapshot:raw];
 NSArray*candles=[payload[@"candles"] isKindOfClass:NSArray.class]?payload[@"candles"]:nil;if(!n&&!candles.count){[self log:@"MARKET FEED rejected: no snapshot/candles"];return;}
 if(n)self.externalMarketSnapshot=n;if(candles.count)self.externalCandles=[candles subarrayWithRange:NSMakeRange(MAX((NSInteger)candles.count-60,0),MIN((NSInteger)candles.count,60))];self.externalMarketUpdatedAt=[NSDate date];
 [self log:[NSString stringWithFormat:@"MARKET FEED update asset=%@ price=%@ payout=%@ candles=%lu",self.externalMarketSnapshot[@"asset"]?:@"—",self.externalMarketSnapshot[@"price"]?:@"—",self.externalMarketSnapshot[@"payout"]?:@"—",(unsigned long)self.externalCandles.count]];
}
- (BOOL)externalFeedFresh{if(!self.externalMarketUpdatedAt)return NO;return -[self.externalMarketUpdatedAt timeIntervalSinceNow]<=15.0;}
- (void)showMarketDataStatus{
 NSDictionary*s=[self externalFeedFresh]?self.externalMarketSnapshot:nil;
 if(!s){[self log:@"MARKET DATA: waiting for authorized feed; UI fallback remains active"];self.statusLabel.text=@"Market feed: UI fallback";return;}
 [self log:[NSString stringWithFormat:@"MARKET DATA: asset=%@ price=%@ amount=%@ expiry=%@ payout=%@",s[@"asset"]?:@"—",s[@"price"]?:@"—",s[@"investment"]?:@"—",s[@"expiry"]?:@"—",s[@"payout"]?:@"—"]];
 self.statusLabel.text=@"Market feed: external snapshot";
}
- (BOOL)has:(NSString*)s words:(NSArray*)ws{NSString*u=s.uppercaseString;for(NSString*w in ws)if([u containsString:w.uppercaseString])return YES;return NO;}
- (UIView*)interactiveAncestor:(UIView*)v{UIView*x=v;for(int i=0;i<8&&x;i++,x=x.superview){if([x isKindOfClass:UIControl.class]||x.gestureRecognizers.count>0||x.isAccessibilityElement)return x;}return nil;}
- (NSDictionary*)dictForView:(UIView*)v text:(NSString*)tx{CGRect r=[v convertRect:v.bounds toView:nil];return@{@"view":v,@"class":NSStringFromClass(v.class)?:@"",@"text":tx?:@"",@"x":@(r.origin.x),@"y":@(r.origin.y),@"w":@(r.size.width),@"h":@(r.size.height)};}
- (NSString*)firstText:(NSArray*)a words:(NSArray*)ws{for(NSDictionary*d in a)if([self has:d[@"text"] words:ws])return d[@"text"];return@"—";}
- (void)scanSafe{UIWindow*w=[self hostWindow];if(!w){[self log:@"SCAN: EO window missing"];return;}NSMutableArray*a=[NSMutableArray array];[self walk:w out:a depth:0];self.lastCandidates=a;NSDictionary*ui=[self autoTextSnapshot:a];NSMutableDictionary*merged=[ui mutableCopy];NSDictionary*ext=[self externalFeedFresh]?self.externalMarketSnapshot:nil;for(NSString*k in @[@"asset",@"price",@"investment",@"expiry",@"payout"]){NSString*v=ext[k];if(v.length)merged[k]=v;}self.snapshot=merged;
NSArray*buy=@[@"شراء",@"BUY",@"CALL"],*sell=@[@"بيع",@"SELL",@"PUT"];for(NSDictionary*d in a){NSString*tx=d[@"text"];UIView*v=d[@"view"];if(!self.buyTarget&&[self has:tx words:buy]){UIView*p=[self interactiveAncestor:v];if(p)self.buyTarget=[self dictForView:p text:tx];}if(!self.sellTarget&&[self has:tx words:sell]){UIView*p=[self interactiveAncestor:v];if(p)self.sellTarget=[self dictForView:p text:tx];}}
NSDictionary*ss=self.snapshot?:@{};NSString*asset=ss[@"asset"]?:@"—",*price=ss[@"price"]?:@"—",*investment=ss[@"investment"]?:@"—",*expiry=ss[@"expiry"]?:@"—",*payout=ss[@"payout"]?:@"—";
self.marketLabel.text=[NSString stringWithFormat:@"Asset: %@  Price: %@\nAmount: %@  Expiry: %@\nPayout: %@  BUY:%@ SELL:%@",asset,price,investment,expiry,payout,self.buyTarget?@"mapped":@"—",self.sellTarget?@"mapped":@"—"];
[self log:[NSString stringWithFormat:@"SCAN views=%lu BUY=%@ SELL=%@",(unsigned long)a.count,self.buyTarget?self.buyTarget[@"class"]:@"none",self.sellTarget?self.sellTarget[@"class"]:@"none"]];}
- (void)test:(BOOL)buy{[self scanSafe];NSDictionary*d=buy?self.buyTarget:self.sellTarget;NSString*n=buy?@"BUY":@"SELL";if(!d){[self log:[NSString stringWithFormat:@"%@ blocked: target not mapped",n]];return;}UIView*v=d[@"view"];if([v isKindOfClass:UIControl.class]){[(UIControl*)v sendActionsForControlEvents:UIControlEventTouchUpInside];[self log:[NSString stringWithFormat:@"%@ dispatched UIControl",n]];}else{[self log:[NSString stringWithFormat:@"%@ mapped to %@ but no public UIControl dispatcher; no trade sent",n,d[@"class"]]];}}
- (void)testBuy{[self test:YES];}- (void)testSell{[self test:NO];}

- (void)collectTextFromView:(UIView*)v into:(NSMutableArray*)a depth:(NSInteger)d{if(!v||d>4)return;NSString*t=[self text:v];if(t.length&&![a containsObject:t])[a addObject:t];for(UIView*s in v.subviews)[self collectTextFromView:s into:a depth:d+1];}
- (NSString*)mappedValue:(NSString*)key{NSDictionary*d=self.dataTargets[key];UIView*v=d[@"view"];if(!v||!v.window)return @"—";NSMutableArray*a=[NSMutableArray array];[self collectTextFromView:v into:a depth:0];UIView*x=v.superview;for(int i=0;i<2&&x;i++,x=x.superview)[self collectTextFromView:x into:a depth:0];NSString*s=[a componentsJoinedByString:@" | "];return s.length?s:@"—";}
- (void)captureSnapshot{[self scanSafe];NSDictionary*s=self.snapshot?:@{};NSString*asset=s[@"asset"]?:@"—",*price=s[@"price"]?:@"—",*amount=s[@"investment"]?:@"—",*expiry=s[@"expiry"]?:@"—",*payout=s[@"payout"]?:@"—";self.marketLabel.text=[NSString stringWithFormat:@"Asset: %@  Price: %@\nAmount: %@  Expiry: %@\nPayout: %@  BUY:%@ SELL:%@",asset,price,amount,expiry,payout,self.buyTarget?@"mapped":@"—",self.sellTarget?@"mapped":@"—"];[self log:[NSString stringWithFormat:@"SNAPSHOT asset=%@ price=%@ amount=%@ expiry=%@ payout=%@",asset,price,amount,expiry,payout]];}
- (void)mapData{self.mapQueue=@[@"ASSET",@"PRICE",@"AMOUNT",@"EXPIRY",@"PAYOUT"];self.mapIndex=0;[self beginMapStep];}
- (void)beginMapStep{if(self.mapIndex>=self.mapQueue.count){self.panel.hidden=NO;self.bubble.hidden=NO;self.statusLabel.text=@"Data mapping complete • CAPTURE to verify";[self captureSnapshot];return;}NSString*k=self.mapQueue[self.mapIndex];self.learnDirection=[@"DATA:" stringByAppendingString:k];self.statusLabel.text=[NSString stringWithFormat:@"Tap %@ on EO screen",k];self.panel.hidden=YES;self.bubble.hidden=YES;UIWindow*w=[self hostWindow];if(!w)return;UITapGestureRecognizer*g=[[UITapGestureRecognizer alloc]initWithTarget:self action:@selector(captureLearnTap:)];g.cancelsTouchesInView=NO;g.delaysTouchesBegan=NO;g.delaysTouchesEnded=NO;[w addGestureRecognizer:g];self.learnTap=g;}

- (NSString*)pathForView:(UIView*)v{NSMutableArray*a=[NSMutableArray array];UIView*x=v;for(int i=0;i<8&&x;i++,x=x.superview)[a addObject:NSStringFromClass(x.class)?:@"?"];return[a componentsJoinedByString:@" <- "];}
- (void)beginLearn:(NSString*)direction{UIWindow*w=[self hostWindow];if(!w){[self log:@"LEARN blocked: EO window missing"];return;}self.learnDirection=direction;self.statusLabel.text=[NSString stringWithFormat:@"Tap the REAL %@ button now…",direction];self.panel.hidden=YES;self.bubble.hidden=YES;UITapGestureRecognizer*g=[[UITapGestureRecognizer alloc]initWithTarget:self action:@selector(captureLearnTap:)];g.cancelsTouchesInView=NO;g.delaysTouchesBegan=NO;g.delaysTouchesEnded=NO;[w addGestureRecognizer:g];self.learnTap=g;}
- (void)captureLearnTap:(UITapGestureRecognizer*)g{if(g.state!=UIGestureRecognizerStateEnded)return;UIWindow*w=[self hostWindow];CGPoint p=[g locationInView:w];UIView*v=[w hitTest:p withEvent:nil];[w removeGestureRecognizer:g];self.learnTap=nil;NSString*dir=self.learnDirection?:@"?";self.learnDirection=nil;if(v){NSDictionary*d=[self dictForView:v text:[self text:v]];if([dir hasPrefix:@"DATA:"]){NSString*k=[dir substringFromIndex:5];self.dataTargets[k]=d;[self log:[NSString stringWithFormat:@"MAP %@: %@ @ %.0f,%.0f %.0fx%.0f",k,d[@"class"],[d[@"x"]doubleValue],[d[@"y"]doubleValue],[d[@"w"]doubleValue],[d[@"h"]doubleValue]]];[self log:[@"PATH: " stringByAppendingString:[self pathForView:v]]];self.mapIndex++;dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(0.25*NSEC_PER_SEC)),dispatch_get_main_queue(),^{[self beginMapStep];});return;}if([dir isEqualToString:@"BUY"])self.buyTarget=d;else self.sellTarget=d;[self log:[NSString stringWithFormat:@"LEARN %@: %@ @ %.0f,%.0f %.0fx%.0f",dir,d[@"class"],[d[@"x"]doubleValue],[d[@"y"]doubleValue],[d[@"w"]doubleValue],[d[@"h"]doubleValue]]];[self log:[@"PATH: " stringByAppendingString:[self pathForView:v]]];}else [self log:[NSString stringWithFormat:@"LEARN %@ failed: no view at touch",dir]];dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(0.35*NSEC_PER_SEC)),dispatch_get_main_queue(),^{self.panel.hidden=NO;self.bubble.hidden=NO;self.statusLabel.text=[NSString stringWithFormat:@"%@ learned • CAPTURE to verify",dir];[self captureSnapshot];});}
- (void)learnBuy{[self beginLearn:@"BUY"];}- (void)learnSell{[self beginLearn:@"SELL"];}

- (void)analyzeNow{[self captureSnapshot];NSDictionary*pre=self.snapshot?:@{};for(NSString*k in @[@"asset",@"price",@"investment",@"expiry",@"payout"]){NSString*v=pre[k];if(!v.length||[v isEqualToString:@"—"]){[self log:[NSString stringWithFormat:@"ANALYZE blocked: %@ not mapped/readable",k]];self.statusLabel.text=@"Map all market data before analysis";return;}}NSString*key=[self readKey];if(!key.length){[self log:@"ANALYZE blocked: save NVIDIA key first"];return;}NSDictionary*s=self.snapshot?:@{};NSArray*candles=[self externalFeedFresh]?self.externalCandles:nil;NSData*cd=candles.count?[NSJSONSerialization dataWithJSONObject:candles options:0 error:nil]:nil;NSString*candleJSON=cd?[[NSString alloc]initWithData:cd encoding:NSUTF8StringEncoding]:@"[]";NSString*prompt=[NSString stringWithFormat:@"Analyze this short-duration trading market snapshot. Asset: %@. Live price: %@. Investment: %@. Expiry: %@. Payout: %@. Recent candles (oldest to newest, may be empty): %@. Use only supplied data. Return ONLY compact JSON with keys direction (BUY, SELL, or SKIP), confidence (0 to 1), and reason. Choose SKIP when evidence is insufficient. Do not invent prices or indicators.",s[@"asset"]?:@"unknown",s[@"price"]?:@"unknown",s[@"investment"]?:@"unknown",s[@"expiry"]?:@"unknown",s[@"payout"]?:@"unknown",candleJSON];
NSDictionary*body=@{@"model":EOModel,@"messages":@[@{@"role":@"user",@"content":prompt}],@"chat_template_kwargs":@{@"enable_thinking":@NO},@"max_tokens":@256,@"stream":@NO,@"temperature":@0.2};
NSError*je=nil;NSData*data=[NSJSONSerialization dataWithJSONObject:body options:0 error:&je];if(!data){[self log:@"ANALYZE JSON encode failed"];return;}NSMutableURLRequest*r=[NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"https://integrate.api.nvidia.com/v1/chat/completions"]];r.HTTPMethod=@"POST";r.HTTPBody=data;r.timeoutInterval=45;[r setValue:[@"Bearer " stringByAppendingString:key] forHTTPHeaderField:@"Authorization"];[r setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];[r setValue:@"application/json" forHTTPHeaderField:@"Accept"];self.statusLabel.text=@"Analyzing live snapshot…";[self log:[NSString stringWithFormat:@"ANALYZE → %@",EOModel]];
NSURLSessionDataTask*task=[[NSURLSession sharedSession] dataTaskWithRequest:r completionHandler:^(NSData*d,NSURLResponse*resp,NSError*err){if(err){[self log:[@"NVIDIA error: " stringByAppendingString:err.localizedDescription]];return;}NSInteger code=[(NSHTTPURLResponse*)resp statusCode];if(code<200||code>=300){[self log:[NSString stringWithFormat:@"NVIDIA HTTP %ld",(long)code]];return;}NSDictionary*j=[NSJSONSerialization JSONObjectWithData:d options:0 error:nil];NSString*out=j[@"choices"][0][@"message"][@"content"];if(![out isKindOfClass:NSString.class])out=@"Invalid NVIDIA response";dispatch_async(dispatch_get_main_queue(),^{self.statusLabel.text=@"Analysis complete • no auto execution";[self log:[@"AI: " stringByAppendingString:out]];});}];[task resume];}
@end
__attribute__((constructor))static void EOBOTERInitialize(void){dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(1*NSEC_PER_SEC)),dispatch_get_main_queue(),^{[[EOBOTEROverlay shared]install];});}
